//this will depend on way of accessing the carousel (generated by php)
//direct access to 2nd page ~ number 1 or direct access to 1st page ~ number 0
$('document').ready(function() {
 hash = window.location.hash
 if (hash != '') {
   $("#carousel").carousel(parseInt(hash.substr(2)));  // we expect names like #p1
   if (parseInt(hash.substr(2)) === 0) $('.carousel-control.left').hide();
 } else {
   $('.carousel-control.left').hide();
 }
});

// Hiding the first and last arrow
//http://stackoverflow.com/questions/9860436/twitter-bootstrap-carousel-access-current-index  
$('document').ready(function() {
    $('#carousel').on('slide.bs.carousel',function(e){
      var slideFrom = $(this).find('.item.active').index();
      var slideTo = $(e.relatedTarget).index();
      
      if (slideTo === 0) $('#carousel-control-left').hide();
      else $('#carousel-control-left').show();
      
      //to the last one (weight selection)
      if (slideTo == ($('.item').length - 1)) {
        $('#carousel-control-right').hide();
        //$('#carousel-control-last').show();
        $('.carousel-indicators').hide();
        
      }
      else {
        $('#carousel-control-right').show();
        $('#carousel-control-last').hide();
        $('.carousel-indicators').show();
      }
      
      window.location.hash = '#p' + slideTo;
    });
});


// submit calc also by clicking on the last arrow
$('document').ready(function() {
    $("#carousel-control-last").click(function() {
        document.getElementById("calc").submit();
    });
});
